package com.xworkz.govtschemes;

import com.xworkz.govtschemes.impl.GujrathGovtSchemesImpl;
import com.xworkz.govtschemes.impl.KeralaGovtschemesImpl;
import com.xworkz.govtschemes.impl.RajastanGovtSchemesImpl;
import com.xworkz.govtschemes.impl.UPGovtschemesImpl;

public class CentralGovtschemesExecutor {
    public static void main(String[] args) {

        CentralGovtschemes govt1 = new CentralGovtschemes.KarnatakaGovtschemesImpl();
        govt1.annaBhagya();
        govt1.gruhalakshmi();
        govt1.gruhajyothi();
        govt1.freeEducation();
        govt1.freeFood();
        govt1.freeGas();
        govt1.freeHouse();
        govt1.freeWater();
        govt1.freeBusPass();
        govt1.farmerLoan();
        govt1.womenSafety();
        govt1.youthTraining();
        govt1.freeLaptop();
        govt1.freeCycle();
        govt1.oldAgePension();
        govt1.widowPension();
        govt1.rationScheme();
        govt1.startupSupport();
        govt1.healthInsurance();
        govt1.ayushmanBharat();
        govt1.freeMedicine();
        govt1.roadDevelopment();
        govt1.smartCity();
        govt1.digitalIndia();
        govt1.cleanIndia();
        govt1.employmentScheme();
        govt1.skillDevelopment();
        govt1.irrigationScheme();
        govt1.villageDevelopment();
        govt1.metroDevelopment();
        govt1.womenEmpowerment();
        govt1.housingScheme();
        govt1.studentScholarship();
        govt1.freeElectricity();
        govt1.agricultureSupport();

        CentralGovtschemes govt2 = new GujrathGovtSchemesImpl();
        govt2.annaBhagya();
        govt2.gruhalakshmi();
        govt2.gruhajyothi();
        govt2.freeEducation();
        govt2.freeFood();
        govt2.freeGas();
        govt2.freeHouse();
        govt2.freeWater();
        govt2.freeBusPass();
        govt2.farmerLoan();
        govt2.womenSafety();
        govt2.youthTraining();
        govt2.freeLaptop();
        govt2.freeCycle();
        govt2.oldAgePension();
        govt2.widowPension();
        govt2.rationScheme();
        govt2.startupSupport();
        govt2.healthInsurance();
        govt2.ayushmanBharat();
        govt2.freeMedicine();
        govt2.roadDevelopment();
        govt2.smartCity();
        govt2.digitalIndia();
        govt2.cleanIndia();
        govt2.employmentScheme();
        govt2.skillDevelopment();
        govt2.irrigationScheme();
        govt2.villageDevelopment();
        govt2.metroDevelopment();
        govt2.womenEmpowerment();
        govt2.housingScheme();
        govt2.studentScholarship();
        govt2.freeElectricity();
        govt2.agricultureSupport();

        CentralGovtschemes govt3 = new KeralaGovtschemesImpl();
        govt3.annaBhagya();
        govt3.gruhalakshmi();
        govt3.gruhajyothi();
        govt3.freeEducation();
        govt3.freeFood();
        govt3.freeGas();
        govt3.freeHouse();
        govt3.freeWater();
        govt3.freeBusPass();
        govt3.farmerLoan();
        govt3.womenSafety();
        govt3.youthTraining();
        govt3.freeLaptop();
        govt3.freeCycle();
        govt3.oldAgePension();
        govt3.widowPension();
        govt3.rationScheme();
        govt3.startupSupport();
        govt3.healthInsurance();
        govt3.ayushmanBharat();
        govt3.freeMedicine();
        govt3.roadDevelopment();
        govt3.smartCity();
        govt3.digitalIndia();
        govt3.cleanIndia();
        govt3.employmentScheme();
        govt3.skillDevelopment();
        govt3.irrigationScheme();
        govt3.villageDevelopment();
        govt3.metroDevelopment();
        govt3.womenEmpowerment();
        govt3.housingScheme();
        govt3.studentScholarship();
        govt3.freeElectricity();
        govt3.agricultureSupport();

        CentralGovtschemes govt4 = new UPGovtschemesImpl();
        govt4.annaBhagya();
        govt4.gruhalakshmi();
        govt4.gruhajyothi();
        govt4.freeEducation();
        govt4.freeFood();
        govt4.freeGas();
        govt4.freeHouse();
        govt4.freeWater();
        govt4.freeBusPass();
        govt4.farmerLoan();
        govt4.womenSafety();
        govt4.youthTraining();
        govt4.freeLaptop();
        govt4.freeCycle();
        govt4.oldAgePension();
        govt4.widowPension();
        govt4.rationScheme();
        govt4.startupSupport();
        govt4.healthInsurance();
        govt4.ayushmanBharat();
        govt4.freeMedicine();
        govt4.roadDevelopment();
        govt4.smartCity();
        govt4.digitalIndia();
        govt4.cleanIndia();
        govt4.employmentScheme();
        govt4.skillDevelopment();
        govt4.irrigationScheme();
        govt4.villageDevelopment();
        govt4.metroDevelopment();
        govt4.womenEmpowerment();
        govt4.housingScheme();
        govt4.studentScholarship();
        govt4.freeElectricity();
        govt4.agricultureSupport();

        CentralGovtschemes govt5 = new RajastanGovtSchemesImpl();
        govt5.annaBhagya();
        govt5.gruhalakshmi();
        govt5.gruhajyothi();
        govt5.freeEducation();
        govt5.freeFood();
        govt5.freeGas();
        govt5.freeHouse();
        govt5.freeWater();
        govt5.freeBusPass();
        govt5.farmerLoan();
        govt5.womenSafety();
        govt5.youthTraining();
        govt5.freeLaptop();
        govt5.freeCycle();
        govt5.oldAgePension();
        govt5.widowPension();
        govt5.rationScheme();
        govt5.startupSupport();
        govt5.healthInsurance();
        govt5.ayushmanBharat();
        govt5.freeMedicine();
        govt5.roadDevelopment();
        govt5.smartCity();
        govt5.digitalIndia();
        govt5.cleanIndia();
        govt5.employmentScheme();
        govt5.skillDevelopment();
        govt5.irrigationScheme();
        govt5.villageDevelopment();
        govt5.metroDevelopment();
        govt5.womenEmpowerment();
        govt5.housingScheme();
        govt5.studentScholarship();
        govt5.freeElectricity();
        govt5.agricultureSupport();

    }
}
